spring:
  application:
    name: token-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        ip: ${SPRING_CLOUD_NACOS_DISCOVERY_IP:token-service}
        namespace: public
        register-enabled: true
        heart-beat-timeout: 15000
        heart-beat-interval: 5000
  datasource:
    url: jdbc:mysql://mysql:3306/memeforge?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
server:
  port: 8082  # 服务端口


