spring:
  application:
    name: transaction-service # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        ip: ${SPRING_CLOUD_NACOS_DISCOVERY_IP:transaction-service}
        namespace: public
        register-enabled: true
        heart-beat-timeout: 15000
        heart-beat-interval: 5000
    loadbalancer:
      retry:
        enabled: true
  datasource:
    url: jdbc:mysql://mysql:3306/memeforge?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8083 # 服务端口

# Feign配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: FULL
  httpclient:
    enabled: false
  okhttp:
    enabled: true

# 日志配置
logging:
  level:
    com.memeforge.transactionservice.client: DEBUG
    org.springframework.cloud.openfeign: DEBUG
